const CHANGE_DATE = 'CHANGE_DATE'
const CHANGE_TIME = 'CHANGE_TIME'
const CHANGE_SUM_VALUE = 'CHANGE_SUM_VALUE'
const ADD_NEW_EXPENSE = 'ADD_NEW_EXPENSE'
export {
    CHANGE_DATE,
    CHANGE_SUM_VALUE,
    CHANGE_TIME,
    ADD_NEW_EXPENSE
}
